DataSource:
    mySQLColumnName: username
    mySQLTablename: authme
    mySQLUsername: authme
    backend: file
    mySQLColumnLastLogin: lastlogin
    mySQLDatabase: authme
    mySQLPort: '3306'
    mySQLColumnIp: ip
    mySQLHost: 127.0.0.1
    mySQLColumnPassword: password
    mySQLPassword: '12345'
    caching: true
    mySQLlastlocX: x
    mySQLlastlocY : y
    mySQLlastlocZ : z
    mySQLColumnEmail: email
GroupOptions:
    UnregisteredPlayerGroup: ''
    RegisteredPlayerGroup: ''
    Permissions:
        PermissionsOnJoin: []
settings:
    sessions:
        enabled: false
        timeout: 10
    restrictions:
        allowChat: false
        allowCommands:
        - /login
        - /register
        - /l
        - /reg
        - /passpartu
        - /email
        maxRegPerIp: 1
        maxNicknameLength: 20
        ForceSingleSession: true
        ForceSpawnLocOnJoinEnabled: false
        SaveQuitLocation: false
        AllowRestrictedUser: false
        AllowedRestrictedUser: []
        kickNonRegistered: false
        kickOnWrongPassword: false
        teleportUnAuthedToSpawn: false
        minNicknameLength: 3
        allowMovement: false
        timeout: 30
        allowedNicknameCharacters: '[a-zA-Z0-9_?]*'
        allowedMovementRadius: 100
        enablePasswordVerifier: true
        ProtectInventoryBeforeLogIn: true
        allowedPluginTeleportHandler: false
    GameMode:
        ForceSurvivalMode: false
        ResetInventoryIfCreative: false
    security:
        minPasswordLength: 4
        unLoggedinGroup: unLoggedinGroup
        passwordHash: SHA256
    registration:
        enabled: true
        messageInterval: 5
        force: true
    unrestrictions:
        UnrestrictedName: []
    messagesLanguage: en
ExternalBoardOptions:
    mySQLColumnSalt: ''
    mySQLColumnGroup: ''
    nonActivedUserGroup: -1
permission:
    EnablePermissionCheck: false
BackupSystem:
    ActivateBackup: false
    OnServerStart: false
    OnServerStop: true
    MysqlWindowsPath: 'C:\\Program Files\\MySQL\\MySQL Server 5.1\\'
Passpartu:
    enablePasspartu: false
Security:
    SQLProblem:
        stopServer: true
    ReloadCommand:
        useReloadCommandSupport: true
    Console:
        noConsoleSpam: false
        removePassword: true
Converter:
    Rakamak:
        fileName: users.rak
        useIP: false
        ipFileName: UsersIp.rak
        newPasswordHash: SHA256